global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor


#rule_files:
#  - "django.rules"

scrape_configs:
  - job_name: "main-django"
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - host.docker.internal

  - job_name: "celery-workers"
    metrics_path: /metrics
    basic_auth:
      username: user1
      password: password1
    static_configs:
      - targets:
        - host.docker.internal:5555

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]


