export const AUTH ='AUTH'
export const AUTH_ERROR ='AUTH_ERROR'
export const ACTIVATION ='ACTIVATION'
export const ACTIVATION_ERROR ='ACTIVATION_ERROR'
export const LOG_OUT ='LOG_OUT'
export const TOKEN_VERIFY ='TOKEN_VERIFY'
export const TOKEN_VERIFY_ERROR ='TOKEN_VERIFY_ERROR'
export const RESET_PASSWORD_EMAIL ='RESET_PASSWORD_EMAIL'
export const RESET_PASSWORD_EMAIL_ERROR ='RESET_PASSWORD_EMAIL_ERROR'
export const RESET_PASSWORD_EMAIL_CONFIRMATION ='RESET_PASSWORD_EMAIL_CONFIRMATION'
export const RESET_PASSWORD_EMAIL_CONFIRMATION_ERROR ='RESET_PASSWORD_EMAIL_CONFIRMATION_ERROR'


export const SET_USER = 'SET_USER'
export const PATCH_USER = 'PATCH_USER'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'

export const SET_FILES = 'SET_FILES'
export const SET_FILE = 'SET_FILE'
export const CLEAR_STORE = 'CLEAR_STORE'

